apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-config
data:
  default.conf: |
    server {
        listen 80;

           root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    location /assets/ {
        try_files $uri =404;
    }

        # Credential Issuance API
        location /auth/ {
            proxy_pass http://credential-issuance-service:2000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Credential Verification API
        location /verification/ {
            proxy_pass http://credential-verification-service:2001/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
