# issuance-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: credential-issuance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: credential-issuance
  template:
    metadata:
      labels:
        app: credential-issuance
    spec:
      containers:
      - name: credential-issuance
        image: muhammedziyavudheen/credential-issuance-service:latest
        ports:
        - containerPort: 2000
        env:
        - name: PORT
          value: "2000"
        - name: MONGO_URI
          value: "mongodb+srv://ziyavudheen:ziyavudheen@cluster0.zkekwwj.mongodb.net/kubeCredentils"
---
apiVersion: v1
kind: Service
metadata:
  name: credential-issuance-service
spec:
  type: NodePort
  selector:
    app: credential-issuance
  ports:
  - port: 2000
    targetPort: 2000
    nodePort: 30001
